### ISSUE TITLE
Make permissions more granular

### ISSUE THREAD

**Issue by markdboyd** [Chapabu/Composer-Security-Checker#10]
Right now, the permission to access the Composer Security Checker settings form is "access administration pages". However, for site editor/content manager roles on a site, they may need access to administration pages for content, but we would not want them to access something this kind of configuration that should be reserved for site administrators.

I propose adding a new permission to the new module, "access composer security checker settings", and making access to the settings page based on that permission.

**Comment by markdboyd** [comment]
I opened an issue on drupal.org and included a patch there: https://www.drupal.org/node/2867094

**Comment by Chapabu** [comment]
Issue closed on d.o https://www.drupal.org/node/2867094
